title: Nature rover
hero_image: images/banner.png
description: Use Scratch to create a wilderness scene for a nature rover to explore
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Make the controller
  - title: Scroll the background
  - title: Scroll more sprites
  - title: Collect a sample
  - title: Create another sample
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
