title: Nature rover
hero_image: images/banner.png
description: Use Scratch to create a wilderness scene for a nature rover to explore
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Control the rover
  - title: Scroll the background
    completion: engaged  
  - title: Scroll more sprites
  - title: Collect a sample
  - title: Create another sample
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: internal       
  - title: Upgrade your project
    completion: external  
  - title: What next?
