title: rainforest-rover
hero_image: images/banner.png
description: 
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Make the controller
  - title: Add scrolling
  - title: Collect a tree sample
  - title: Collect a cloud sample
  - title: Create another sample
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
