---
title: नेचर रोव्हर
hero_image: images/banner.png
description: नेचर रोव्हर एक्सप्लोर करण्यासाठी वाळवंटाचे दृश्य तयार करण्यासाठी Scratch वापरा
meta_title: Scratch coding projects for kids and teens | Nature rover
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Create a wilderness scene with Scratch for a nature rover to explore.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: रोव्हर नियंत्रित करा
  - 
    title: बॅकग्राऊंड स्क्रोल करा
    completion:
      - engaged
  - 
    title: अधिक स्प्राईट्स स्क्रोल करा
  - 
    title: नमुना गोळा करा
  - 
    title: दुसरा नमूना तयार करा
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: तुमचा प्रोजेक्ट अपग्रेड करा
