---
title: Rover nature
hero_image: images/banner.png
description: Utiliser Scratch pour créer une scène sauvage à explorer par un rover nature
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - title: Tu feras
  - title: Contrôler le rover
  - title: Faire défiler l'arrière-plan
    completion:
      - engaged
  - title: Faire défiler plus de sprites
  - title: Recueillir un échantillon
  - title: Créer un autre échantillon
    completion:
      - internal
  - title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Améliorer ton projet
  - title: Et ensuite ?
